CREATE TABLE IF NOT EXISTS transaction_analysis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    project_id VARCHAR(255) NOT NULL,
    environment VARCHAR(50) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    analysis_name VARCHAR(255) NOT NULL,
    original_payload LONGTEXT NOT NULL,
    yaml_content LONGTEXT NOT NULL,
    analysis_result LONGTEXT NOT NULL,
    status ENUM('pending', 'processing', 'completed', 'failed') DEFAULT 'pending',
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    token_count INT DEFAULT 0,
    processing_time_ms INT DEFAULT 0,
    INDEX idx_project_env (project_id, environment),
    INDEX idx_user_id (user_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 